classDiagram
    APP <|-- Mc32_sdFatGest
    APP <|-- BNO055_Support
    BNO055_Support <|-- BNO055
    APP <|-- Mc32_PressAdc
    APP <|-- Mc32_serComm

    APP : +APP_DATA appData
    APP : +TIMER_DATA timerData
    APP : +APP_Tasks()
    APP : +MainTimer_callback()
    APP : +DisplayTimer_callback()
    APP: +prepareBuffer()
    APP: +App_resetMeasFlag()
    APP: +APP_Initialize()

    class BNO055_Support{
        
      -bno055_t bno055_data
      +bno055_init_readout()
      +bno055_read_routine()
      +BNO055_delay_msek()
      +I2C_routine()
      -BNO055_I2C_bus_write()
      -BNO055_I2C_bus_read()

    }
    class BNO055{
      Fonctions librairie BOSCH

    }
    class Mc32_sdFatGest{
      -APP_FAT_DATA appFatData
      +sd_fat_task()
      +sd_BNO_scheduleWrite()
      +sd_getState()
      +sd_setState()
    }

    class Mc32_serComm{
      +serDisplayValues()
    }

    class Mc32_PressAdc{
      +S_ADCResults AdcResult
      +Press_voltageToPressure()
      +Press_RawToVoltage()
      +Press_InitADC()
      +Press_ReadAllADC()
      +Press_readPressure()
    }
